### ISSUE TITLE
Please add a README.md with information

### ISSUE THREAD

**Issue by probonopd** [juanma1980/dev#1]
Please add a README.md with information on what this is and what it is trying to accomplish. This will help others who might be interested in contributing. I am curious because it seems to be somehow related to [AppImage](https://appimage.org/). 

Thanks!

**Comment by juanma1980** [comment]
Hi!
There's no readme on this because is for "test/experiment/proof-of-concept".
Time ago I was working on adding support  to appimage for the [LliureX](https://github.com/lliurex) distribution, this repo contains the early and dirty proofs-of-concept. 
Nowadays appimage is fully supported and integrated in our system and this repo is abandoned.

**Comment by probonopd** [comment]
Is there an easy way (e.g., Live ISO) to try out LilureX in English? Can other distributions learn from/use your AppImage integration? Thanks.

**Comment by juanma1980** [comment]
Hi. 
LliureX is not a live distro but you can give it a try from the installation cd choosing the first option at boot menu ("Try LliureX without installing"/"Proveu el LliureX sense intal·lar-lo"/"Probar LliureX sin instalarlo").
By default LliureX boots in valencian language (a variant of Catalan) but you can change it pressing F2 at boot menu. Our own apps are translated to valencian, spanish and english, the rest of the system is translated according to Ubuntu translations.
The stable release is based on Xenial and appimages are not fully integrated, they could been installed and launched using our software store (LliureX-store) but they are downloaded to ~/.local/bin so a non-terminal user have no way to launch them but LliureX-store. If you remember me I'm the one who was trying to convince his team for use appimage. In our new release (based on bionic) appimage is more integrated, the new download path is ~/Appimage and we've developed a basic manager that let users "install" the appimages across the system (that's becasue LliureX is heavily based on LTSP and we need that thin clients can get the apps from the server).
 
That being said you could download our stable release from [our servers](http://mestreacasa.gva.es/web/lliurex/descarregues). I recommend you to choose the desktop flavour (labeled as "escritorio" or "escriptori", latest release is "LliureX 16.06 escriptori64 bits (21/3/2019) (Kernel 4.15)").  

Once booted you could launch "lliurex-store" and search for appimages (by name or simply writting "appimage" in search box). Due a bug on first launch you must wait one minute (more or less) before you could search any appimage. Also there's another bug (fixed in updates but not on live session) that could segfault the store.

Thx, if I've time I'll upload a video with appimage-manager in action.

**Comment by probonopd** [comment]
Thank you @juanma1980, very interesting. I will try it out. Is there any chance you could use `~/Applications` in the future instead of `~/Appimage`? We are trying to standardize on that preferred location. cc fyi @azubieta @TheAssassin

**Comment by juanma1980** [comment]
> Thank you @juanma1980, very interesting. I will try it out. Is there any chance you could use `~/Applications` in the future instead of `~/Appimage`? We are trying to standardize on that preferred location. cc fyi @azubieta @TheAssassin

@probonopd Already updated the sources. ~/Applications is now the default folder for appimages. In LlirueX we respect standards and thermodynamics.

**Comment by probonopd** [comment]
Thank you.
